from selenium import webdriver
import pyautogui
from time import sleep

chrome_options = webdriver.ChromeOptions()
chrome_options.add_extension(r"C:\Users\gkush\Downloads\ad.crx")
chrome_options.add_extension(r"C:\Users\gkush\Downloads\a.crx")
username=input("Enter the Tiktok username: ")
driver = webdriver.Chrome(r"C:\Users\gkush\Downloads\chromedriver.exe", options=chrome_options)
driver.set_window_size(560,720)
driver.get(f'https://www.tiktok.com/{username}')
sleep(2)
pyautogui.click(422,70)
sleep(2)
pyautogui.click(253,379)
sleep(2)
pyautogui.click(169,37)

    
sleep(2)
# pyautogui.displayMousePosition()
pyautogui.click(461,67)
sleep(1)
pyautogui.click(200,135)
sleep(2)
pyautogui.click(234,289)
sleep(2)
pyautogui.click(11,269)
sleep(4)
pyautogui.click(104,73)
sleep(5)
# pyautogui.click(499,681)
# sleep(2)
# sleep(2)
# driver.find_element_by_xpath('//*[@id="main"]/div[2]/div/button').click()
sleep(5)
driver.find_element_by_xpath('//*[@id="main"]/div/div/div[2]/div[2]/span').click()
sleep(5)
driver.find_element_by_xpath('//*[@id="main"]/div/div/div/div[3]/div/li[1]/a').click()
sleep(2)
for i in range(1,100):
    sleep(2)
    pyautogui.click(104,73)
    sleep(5)
    driver.find_element_by_xpath('//*[@id="main"]/div/div/div/div[3]/div/li[1]/a').click()
    # driver.find_element_by_xpath('//*[@id="main"]/div[2]/div/div[1]/div/div[1]/div[3]/span').click()
    sleep(16)
